### ISSUE TITLE
Repeating calls to "on change" for multi-byte integers 

### ISSUE THREAD

**Issue by oatspear** [gamehook-io/gamehook#5]
**Context:** declared a 2-byte `int` in mapper file for GB.

**Expected:** receive `onChange` calls when the value changes.

**Observed:** constant calls always with the same value.

**Example:**
Mapper for Pokémon Crystal. Declare:

```yaml
musicID: { type: "int", address: 0xC29D, size: 2 }
```

This does not happen if I change it to a single byte value.

```yaml
musicID: { type: "int", address: 0xC29D, size: 1 }
```

**Comment by flamesage** [comment]
@oatspear This should now be resolved in [2022.7.17.1-beta](https://github.com/gamehook-io/gamehook/releases/tag/2022.7.17.1-beta). Could you test this?

**Comment by Scotts-Thoughts** [comment]
@flamesage are we still using `.onChange()`? I believe it was deprecated many builds ago when `.change()` was introducted.

**Comment by flamesage** [comment]
> @flamesage are we still using `.onChange()`? I believe it was deprecated many builds ago when `.change()` was introduced. 

It is, but this bug was created when it was still around. 

The root cause of the bug was two issues:

1) I was comparing arrays using `==` which compares by reference, not by value.
2) The endianness of the bytes were reversed in the old code. This now only happens inside of translation, so the endianness is now preserved.

**Comment by flamesage** [comment]
@oatspear Still wanted to follow up to make sure this is fixed.

**Comment by oatspear** [comment]
@flamesage, it seems to be working. Thanks :+1:
